/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit;

import junit.framework.TestCase;
import junit.framework.TestSuite;
import org.junit.runner.RunWith;
import org.junit.runners.AllTests;

@RunWith(AllTests.class)
public class JUnit3Test extends TestCase {

    public JUnit3Test(String name) {
        super(name);
    }

    public static TestSuite suite()
    {
        var suite = new TestSuite("JUnit 3 style test suite");
        suite.addTest(new JUnit3Test("JUnit 3 style test") {
            @Override
            protected void runTest() {
                testSomeLibraryMethodReturnsTrue();
            }
        });
        return suite;
    }

    public void testSomeLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
